model:
  embed_dim: 4
  lossconfig:
    disc_start: 50001
    kl_weight: 0.000001
    disc_weight: 0.5
    disc_in_channels: 1
  ddconfig:
    double_z: True
    z_channels: 4
    resolution: [1024, 1024]
    in_channels: 1
    out_ch: 1
    ch: 128
    ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
  ckpt_path: '/home/zhuchenyang/project/hyx/data/pretrain_weights/model-kl-d8.ckpt'

data:
  name: edge
  img_folder: '/home/zhuchenyang/project/hyx/data/total_edges'
  augment_horizontal_flip: True
  batch_size: 1

trainer:
  gradient_accumulate_every: 8
  lr: !!float 5e-6
  min_lr: !!float 1e-6
  train_num_steps: 200000
  save_and_sample_every: 10000
  log_freq: 100
  results_folder: '/home/zhuchenyang/project/hyx/data/total_edges/results_ae_kl_adaptive_size_d8'
  amp: False
  fp16: False