model:
  class_name: ddm.ddm_const.DDPM
  image_size: [32, 32]
  ckpt_path:
  ignore_keys: []
  only_model: False
  sampling_timesteps: 10
  loss_type: l2
  start_dist: normal
  perceptual_weight: 1.0
  eps: !!float 1e-4
  sigma_max: 1
  sigma_min: 0.01
  ldm: False
  weighting_loss: True
  use_l1: False
  use_augment: True
  unet:
    class_name: unet.uncond_unet.EDMPrecond
    img_resolution: 32
    img_channels: 3
    sigma_data: 1.0  # Expected standard deviation of the training data.
    model_type: 'DhariwalUNet'
    model_channels: 192  # Base multiplier for the number of channels.
    channel_mult: [1, 2, 2, 2]
    channel_mult_emb: 4  # Multiplier for the dimensionality of the embedding vector.
    num_blocks: 3  # Number of residual blocks per resolution.
    attn_resolutions: [16, 8]  # List of resolutions with self-attention.
    dropout: 0.1  # List of resolutions with self-attention.
    label_dropout: 0
    augment_dim: 9
    #ckpt_path: "/nfs/data/pretrain_weight/cifar10_ncsnpp_deep_continuous.pth"

data:
  class_name: ddm.data.CIFAR10
  image_size: [32, 32]
  img_folder: '/data/huang/cifar-10-python/'
  augment_horizontal_flip: True
  batch_size: 128
  num_workers: 8

eval:
  begin_ckpt: 15
  end_ckpt: 35
  num_samples: 50000
  batch_size: 128
  use_ema: True
  workdir: "/data/huang/cifar-10-python/results_ddm_const_uncond_unet"
  gt_stats:
  #  gt_stats: "/data/huang/cifar-10-python/results_etp_const_sde4_ncsnpp10/gt_feature.pth"

trainer:
  gradient_accumulate_every: 2
  lr: !!float 1e-4
  min_lr: !!float 5e-6
  train_num_steps: 800000
  save_and_sample_every: 10000
  log_freq: 500
  results_folder: "/data/huang/cifar-10-python/results_ddm_const_uncond_unet"
  amp: False
  fp16: False
  resume_milestone: 0
  test_before: True
  ema_update_after_step: 10000
  ema_update_every: 8

sampler:
  batch_size: 128
  sample_num: 50000
  use_ema: True
  test_in_train: False
  ckpt_path: "/data/huang/cifar-10-python/results_ddm_const_uncond_unet/model-80.pt"
  save_folder: "/data/huang/cifar-10-python/results_ddm_const_uncond_unet"
  target_path: "/data/huang/cifar-10-python/cifar-10-train-png"