model:
  class_name: ddm.encoder_decoder.AutoencoderKL
  embed_dim: 3
  lossconfig:
    disc_start: 40001
    kl_weight: 0.000001
    disc_weight: 0.5
    disc_in_channels: 1
  ddconfig:
    double_z: True
    z_channels: 3
    resolution: [384, 384]
    in_channels: 1
    out_ch: 1
    ch: 128
    ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
  ckpt_path: #'/home/zhuchenyang/project/hyx/data/pretrain_weights/model-kl-d4.ckpt'

data:
  class_name: ddm.data.DUTSDataset
  image_size: [384, 384]
  data_root: '/nfs/data/diffusion_data/DUTS/'
  split: 'train'
  augment_horizontal_flip: True
  batch_size: 8

trainer:
  gradient_accumulate_every: 2
  lr: !!float 5e-6
  min_lr: !!float 5e-7
  train_num_steps: 80000
  save_and_sample_every: 8000
  log_freq: 200
  results_folder: '/nfs/data/diffusion_data/DUTS/results_DUTS_ae_kl_384x384_d4'
  amp: False
  fp16: False